# Generated by Django 5.2.3 on 2025-06-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_abbr', models.CharField(max_length=10, unique=True)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField()),
                ('down', models.IntegerField(blank=True, null=True)),
                ('ydstogo', models.FloatField(blank=True, null=True)),
                ('yardline_100', models.FloatField(blank=True, null=True)),
                ('qtr_seconds_remaining', models.IntegerField(blank=True, null=True)),
                ('half_seconds_remaining', models.IntegerField(blank=True, null=True)),
                ('game_seconds_remaining', models.IntegerField(blank=True, null=True)),
                ('score_differential', models.FloatField(blank=True, null=True)),
                ('posteam_timeouts_remaining', models.IntegerField(blank=True, null=True)),
                ('defteam_timeouts_remaining', models.IntegerField(blank=True, null=True)),
                ('shotgun', models.BooleanField(default=False)),
                ('no_huddle', models.BooleanField(default=False)),
                ('goal_to_go', models.BooleanField(default=False)),
                ('play_type', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('posteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
