# Generated by Django 5.2.3 on 2025-07-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_play_quarter_seconds_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='time',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
