# Generated by Django 5.2.3 on 2025-07-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='posteam_type',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
