# Generated by Django 5.2.3 on 2025-07-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_play_posteam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='posteam_type',
        ),
    ]
