# Generated by Django 5.2.3 on 2025-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_play_posteam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='clock_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='is_losing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='late_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='long_yardage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='medium_yardage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='quarter_half',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='red_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='short_yardage',
            field=models.BooleanField(default=False),
        ),
    ]
