# Generated by Django 5.2.3 on 2025-07-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_play_clock_pressure_play_is_losing_play_late_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='defteam',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
